Stop up/down vote repetition
covidresources-in/CR-tech-force-frontend pull request #21
Opened 2021-05-01 15:06 UTC by yadavravi2801

Stop upVote/downVote repeatedly from the same user

2021-05-01 15:10 UTC, yadavravi2801 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Improvement: Try to stop upVote/downVote repeatedly from same user](https://trello.com/c/ZhJQ4inG/43-improvement-try-to-stop-upvote-downvote-repeatedly-from-same-user)

2021-05-01 15:21 UTC, varora1406 requested changes

2021-05-01 15:21 UTC, varora1406 commented on src/components/SearchResultsCard/SearchResultCard.jsx
> +    let allowVote = localStorage.getItem(`allowVote_${ticketId}`);
can we keep a single array in localStorage, instead of keeping multiple keys?
Multiple keys will flood it and make it difficult for next developer to understand or work with

2021-05-01 15:21 UTC, varora1406 commented on src/components/SearchResultsCard/SearchResultCard.jsx
> +    }
I thought about different approaches - showing alert, disabling action, and one more - showing already action done as highlighted (like you get blue thumbsup/thumbsdown in facebook)

After thinking for while, I believe showing action done as primary colored already, tells user whether they have already voted anything for that or not. That gives them info, that they have already checked it out.
I am suggesting this, keeping our maximum mobile users in mind. Who can normally make mistake of clicking on icon while scrolling, and can get noisy popups OR get to confused if they see disabled action here.

Relating it to social media's behavior will give good benefit to us here.

-------------------------------------------------------------------------
Technical aspect :
This means you need to store realtime if user has already clicked that ticket or not.
Show that user that thumsup/thumsdown highlighted with primary color if already clicked.
And on clicking them as well, it should do opposite action, and non-highlight that icon again (Back to normal state).

2021-05-05 05:47 UTC, yadavravi2801 commented on src/components/SearchResultsCard/SearchResultCard.jsx
> +    let allowVote = localStorage.getItem(`allowVote_${ticketId}`);
@varora1406 Above modifications are done.

2021-05-05 05:48 UTC, yadavravi2801 commented on src/components/SearchResultsCard/SearchResultCard.jsx
> +    }
@varora1406 Updates done as per your suggestion.

2021-05-05 15:42 UTC, varora1406 approved these changes

2021-05-05 15:42 UTC, varora1406 commented on src/components/SearchResultsCard/SearchResultCard.jsx
> +    let voteUpdateBy = 1;
it's value is not changing, it can be kept as `const`

2021-05-05 15:42 UTC, varora1406 commented on src/components/SearchResultsCard/SearchResultCard.jsx
> +    let voteUpdateBy = 1;
not important for now, but good for next time

2021-05-05 15:43 UTC, merged