PR for Beta branch
covidresources-in/CR-tech-force-frontend pull request #34
Opened 2021-05-13 09:43 UTC by bornfree

@varora1406 

Changes done as per Trello card.
https://trello.com/c/lQhV1N5C/90-card-view-changes-to-show-more-useful-data
Pl review and merge.

2021-05-13 09:53 UTC, varora1406 commented
@bornfree I don't see box shadow in card design in trello. It only has border color.
I find it odd. If you suggest we should have it, can you show Ashish (our designer) once?

2021-05-13 12:37 UTC, bornfree commented
@varora1406 
- Changed the shadow to border
- I took some liberty with the colors of upvote and downvote buttons after they have been clicked. Because we are using SVGs and not icon-fonts, changing icon color would need extra work of switching images. Maybe we can add it in next iteration?

2021-05-13 17:25 UTC, varora1406 commented
hey @bornfree ,
I checked the color, and I see dark complexion it adds to appearance
We have blue header for highlighting header. I believe using back red and green color gives more significance to icon whether it is helpful card marked by you or not
I am afraid, I align to side where I believe we will have to change it.
But if you still believe above point is not convincing, please free to talk in detail with Ashish.
From solution perspective -
you can use https://material-ui.com/components/material-icons/#material-icons and bring the color part as red and green ?

2021-05-13 17:29 UTC, varora1406 requested changes

2021-05-13 17:29 UTC, varora1406 commented on src/components/SearchResultsCard/SearchResultCard.jsx
> +            :null}
Reason of why many fields value have below type of code
`{value || '-'}`
is because of keeping card lengths as same, and give empty fields as '-' instead of hiding field header.

Now I see it's changing, can you tell me the reason?

2021-05-13 19:03 UTC, bornfree commented
Replaced the SVGs with Material UI icons.

I have an observation however.
I believe we are being too pedantic over a product that needs to ship fast. Cosmetic changes can be ignored IMO if it favors faster deploys/fixes to live site. We can always change them if we don't like them.

On te other comment:

The reason `{value? <Component/> : null }` checks have been added is because I interpreted `Do not show fields where "No info Available"` to be so.
I agree this leads to variable heights but it might be acceptable for the following reasons
- Saves the user time and attention but not having to see empty fields
- Heights won't matter on mobile where most users are coming from.

What do you think?

2021-05-14 10:22 UTC, varora1406 commented
You made a strong point, we will go with this one @bornfree 👍

One more thing I found in preview here, that there is extra white space when I am searching leads in search card.
Is it intentional or mistake?
![image](https://user-images.githubusercontent.com/24986539/118257468-4b06d880-b4cc-11eb-8f16-19ba501e7f94.png)

2021-05-14 12:55 UTC, bornfree commented
Just fixed the empty div. It won't render now unless conditions are met.

2021-05-14 13:32 UTC, merged